name: .NET Build Pipeline

on:
  push:
    branches:
      - develop
      - release
    tags:
      - '*' 
  workflow_dispatch:  

jobs:
  build:
    uses: palash150403/git-nexus-task/.github/workflows/build-pack.yml@test

  sonarcloud:
    needs: build
    uses: palash150403/git-nexus-task/.github/workflows/scan.yml@test     
    secrets: 
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }} 
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  push_to_nexus:
    needs: sonarcloud
    uses: palash150403/git-nexus-task/.github/workflows/push-nexus.yml@test
    secrets:
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }} 
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}
    with:
      NEXUS_URL_DEVELOP: ${{ vars.NEXUS_URL_DEVELOP }}
      NEXUS_URL_MAIN: ${{ vars.NEXUS_URL_MAIN }}
      NEXUS_URL_RELEASE: ${{ vars.NEXUS_URL_RELEASE }}